FROM docker.io/nginx:alpine

# 複製本地構建的產物
COPY dist /usr/share/nginx/html

# 複製 nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 複製自定義啟動腳本
COPY docker-entrypoint.sh /custom-entrypoint.sh
RUN chmod +x /custom-entrypoint.sh

EXPOSE 80

CMD ["/custom-entrypoint.sh"]
